server:
  port: 8080

delta:
  tables:
    ShopUserTransactionPath: s3a://delta/analysis/shop_user_transaction/

spark:
  cluster:
    URL: local[*]
  maxSparkSessionInstances: 10
s3a:
  URL: http://localhost:9000
  accessKey: cUvuW91maGUzCPVc
  secretKey: CcVrQbQS5u90fsTaXDnpWgFOBq6cS9lE


management:
  server:
    port: 9095
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  swagger-ui:
    operationsSorter: method
